# Generated by Django 2.1.7 on 2019-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField()),
                ('positive_small_field', models.PositiveSmallIntegerField()),
                ('big_integer_fiels', models.BigIntegerField()),
                ('float_feils', models.FloatField()),
                ('bitary_feild', models.BinaryField()),
                ('boolean_feild', models.BooleanField()),
                ('char_feild', models.CharField(max_length=5)),
                ('text_feild', models.TextField(max_length=20)),
                ('date_field', models.DateField()),
                ('datre_time_fiels', models.DateTimeField()),
                ('decimal_feild', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email_feils', models.EmailField(max_length=254)),
                ('file_feild', models.FileField(upload_to='')),
                ('image_feild', models.ImageField(upload_to='')),
            ],
        ),
    ]
