# Generated by Django 2.1.7 on 2019-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sutname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('company', models.CharField(choices=[('ep', 'Epam'), ('MS', 'Microsoft'), ('A', 'Apple'), ('I', 'IBM'), ('US', 'Ubisoft')], max_length=150)),
                ('position', models.CharField(choices=[('FD', 'frontEnd-developer'), ('BD', 'backEnd-developer'), ('JS', 'JavaScript-develoter')], max_length=15)),
                ('language', models.CharField(choices=[('c++', 'C++'), ('c#', 'C-sharp'), ('JS', 'JavaScript'), ('PT', 'Pithon'), ('JV', 'Java')], default=('c#', 'C-sharp'), max_length=10)),
                ('salary', models.ImageField(upload_to='')),
            ],
        ),
    ]
